// <auto-generated />
namespace ORM01.Infra.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Adicionando_CPF_Em_Aluno : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Adicionando_CPF_Em_Aluno));
        
        string IMigrationMetadata.Id
        {
            get { return "201806262003362_Adicionando_CPF_Em_Aluno"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
