// <auto-generated />
namespace NDDResearch.Infra.Data.Initializer
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Supporti18n : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Supporti18n));
        
        string IMigrationMetadata.Id
        {
            get { return "201801261934524_Support i18n"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
