// <auto-generated />
namespace Pizzaria.Infra.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class PizzariaBD_Apollo_v1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PizzariaBD_Apollo_v1));
        
        string IMigrationMetadata.Id
        {
            get { return "201807102241137_PizzariaBD_Apollo_v1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
